LOG_FOLDER_NAME = "logs"
USER_AGENT = "RemindMeBot (by /u/Watchful1)"
OWNER = "Watchful1"
DATABASE_NAME = "database.db"
MESSAGE_LINK = "https://www.reddit.com/message/messages/"
ACCOUNT_NAME = "Watchful1BotTest"
TRIGGER = "RemindMe"
TRIGGER_LOWER = TRIGGER.lower()
TRIGGER_RECURRING = "RemindMeRepeat"
TRIGGER_RECURRING_LOWER = TRIGGER.lower()
BACKUP_FOLDER_NAME = "backup"
BLACKLISTED_ACCOUNTS = ['[deleted]', 'kzreminderbot']
