LOG_FOLDER_NAME = "logs"
USER_AGENT = "RemindMeBot (by /u/Watchful1)"
OWNER = "Watchful1"
LOOP_TIME = 60*2
DATABASE_NAME = "database.db"
DATABASE_DEBUG_NAME = "database_debug.db"
MESSAGE_LINK = "https://www.reddit.com/message/messages/"
ACCOUNT_NAME = "Watchful1BotTest"
TRIGGER = "ReminderTest"#"RemindMe"
TRIGGER_LOWER = TRIGGER.lower()
